--------------------------------------------CREATE DATABASE --------------------------------------------------
USE master
IF EXISTS(SELECT * FROM sys.databases WHERE name='quanlyphongkham_final')
DROP DATABASE quanlyphongkham_final
CREATE DATABASE quanlyphongkham_final
GO

USE quanlyphongkham_final
GO


--CTRL+SHIFT+U DE IN HOA, CTRL+SHIFT+L DE IN THUONG
GO

-------------------------------------------- CREATE TABLES --------------------------------------------------
--1.TẠO BẢNG TAIKHOAN
CREATE TABLE TAIKHOAN(
	MATK INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TENDANGNHAP VARCHAR(50) NOT NULL,
	MATKHAU VARCHAR(50) NOT NULL,
	TENHIENTHI NVARCHAR(50) NULL,
	MAPHANQUYEN INT DEFAULT 1, --TÀI KHOẢN THƯỜNG
	TRANGTHAI BIT DEFAULT 1,-- HOẠT ĐỘNG
)
GO


--2 TẠO BẢNG PHANQUYEN
CREATE TABLE PHANQUYEN(
	MAPHANQUYEN INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	QUYEN INT DEFAULT 1, --TÀI KHOẢN THƯỜNG
	GHICHU NVARCHAR(250) NULL,
)
GO

--3 TẠO BẢNG HINHTHUCKHAM

CREATE TABLE HINHTHUCKHAM(
	MAHINHTHUCKHAM int IDENTITY(1,1) NOT NULL,
	TENHINHTHUCKHAM nvarchar(100) NULL
	PRIMARY KEY (MAHINHTHUCKHAM)
) 
GO



--4 TẠO BẢNG PHIEUKHAM -- THÊM TRƯỜNG DATHANHTOAN BIT
CREATE TABLE PHIEUKHAM(
	MAPHIEUKHAM int IDENTITY(1,1) NOT NULL,
	MABN int NULL,
	MANV int NULL,
	CHUANDOAN nvarchar(250) NULL,
	MAHINHTHUCKHAM int NULL,
	NGAYKHAM date NULL,
	KETLUAN nvarchar(50) NULL,
	HOANTHANH bit NULl,
	DATHANHTOAN bit NULL
	PRIMARY KEY (MAPHIEUKHAM)
)
GO
GO

--5 TẠO BẢNG HOADON
CREATE TABLE HOADON(
	MAHOADON INT IDENTITY(1,1) NOT NULL,
	MAPHIEUKHAM INT NOT NULL,
	TONGCONG MONEY NULL
	PRIMARY KEY (MAHOADON)
)
GO

--6 TẠO BẢNG CHITIETDICHVUCLS
CREATE TABLE CHITIETCLS(
	MADICHVUCLS INT,
	MACLS INT,
	KETQUA VARCHAR(250),
	PRIMARY KEY (MADICHVUCLS,MACLS)
)
GO

--7 TẠO BẢNG DICHVUCLS
CREATE TABLE DICHVUCLS(
	MADICHVUCLS INT PRIMARY KEY IDENTITY(1,1),
	MAPHIEUKHAM INT, 
	TONGCONG MONEY
)
GO

--8 TẠO BẢNG CANLAMSANG
CREATE TABLE CANLAMSANG(
	MACLS INT PRIMARY KEY IDENTITY(1,1),
	TENCLS NVARCHAR(250),
	GIATIEN MONEY,
	MALOAICLS INT
)
GO

--9 TẠO BẢNG LOAICANLAMSANG
CREATE TABLE LOAICANLAMSANG(
	MALOAICLS INT PRIMARY KEY IDENTITY(1,1),
	TENLOAI NVARCHAR(250)
)
GO

--10 TẠO BẢNG KHOA
CREATE TABLE KHOA(
	MAKHOA INT PRIMARY KEY IDENTITY(1,1),
	TENKHOA NVARCHAR(100)
)
GO

--11 TẠO BẢNG NHANVIEN
CREATE TABLE NHANVIEN(
MANV INT IDENTITY(1,1) NOT NULL,
	HOTEN NVARCHAR(50) NULL,
	GIOITINH BIT NULL,
	SODT VARCHAR(20) NULL,
	EMAIL VARCHAR(50) NULL,
	MAKHOA INT NULL,
	MACHUCDANH INT NULL,
	MACHUCVU INT NULL,
	PRIMARY KEY (MANV)
)
GO

--12 TẠO BẢNG CHUCDANH
CREATE TABLE CHUCDANH(
MACHUCDANH INT IDENTITY(1,1) NOT NULL,
	TENCHUCDANH NVARCHAR(50) NULL,
	PRIMARY KEY (MACHUCDANH)
)
GO


--13 TẠO BẢNG BENHNHAN
CREATE TABLE BENHNHAN(
	MABN INT IDENTITY(1,1) NOT NULL,
	HOTEN NVARCHAR(50) NULL,
	GIOITINH BIT DEFAULT 1,--NAM
	NGAYSINH DATE NULL,
	DANTOC NVARCHAR(50) DEFAULT 'Kinh',
	SOCMND NVARCHAR(20) NULL,
	DIACHI NVARCHAR(250) NULL,
	SODT VARCHAR(20) NULL
	PRIMARY KEY (MABN)
)
GO

--14 TẠO BẢNG CHUCVU
CREATE TABLE CHUCVU(
	MACHUCVU INT IDENTITY(1,1) NOT NULL,
	TENCHUCVU NVARCHAR(50) NULL,
	PRIMARY KEY (MACHUCVU)
) 
GO




--15 TẠO BẢNG PHIEUNHAP
CREATE TABLE PHIEUNHAP(
	MAPHIEUNHAP INT IDENTITY(1,1) NOT NULL,
	MANV INT NULL,
	NGAYNHAP DATE NULL,
	PRIMARY KEY (MAPHIEUNHAP)
)
GO



--16 TẠO BẢNG DONTHUOC
CREATE TABLE DONTHUOC(
	MADONTHUOC INT IDENTITY(1,1)  PRIMARY KEY NOT NULL,
	MAPHIEUKHAM INT NOT NULL,
	TONGCONG MONEY
)
GO

--17 TẠO BẢNG CHITIETDONTHUOC
CREATE TABLE CHITIETDONTHUOC(
	MADONTHUOC INT not null,
	MATHUOC INT not null,
	SOLUONG INT,
	HUONGDAN TEXT,
	CONSTRAINT CTDT_MADONTHUOC_MATHUOC_PK PRIMARY KEY(MADONTHUOC, MATHUOC)
)
GO

--18 TẠO BẢNG CHITIETNHAPVATTU
CREATE TABLE CHITIETNHAPVATTU(
	MAPHIEUNHAP INT NOT NULL,
	MAVTYT INT NOT NULL,
	SOLUONG INT,
	MAHSX INT,
	NGAYSX DATE,
	NGAYHETHAN DATE,
	GIANHAP MONEY,
	MANHACC INT,
	PRIMARY KEY(MAPHIEUNHAP,MAVTYT)
)
GO

--19 TẠO BẢNG DONVITINH
CREATE TABLE DONVITINH(
MADVT INT IDENTITY PRIMARY KEY NOT NULL,
TENDVT NVARCHAR(50)
)
GO


--20 TẠO BẢNG VATTUYTE
CREATE TABLE VATTUYTE(
	MAVTYT INT PRIMARY KEY IDENTITY(1,1),
	TENVATTU NVARCHAR(250),
	MADVT INT, 
	SOLUONGTON INT
)
GO

--21 TẠO BẢNG THUOC
CREATE TABLE THUOC(
	MATHUOC INT IDENTITY(1,1)  PRIMARY KEY NOT NULL,
	TENTHUOC NVARCHAR(50) NOT NULL,
	DONVITINH INT ,
	LOAITHUOC INT ,
	SOLUONGTON INT ,
	GHICHU TEXT
)
GO

--22 TẠO BẢNG CHITIETNHAPTHUOC
CREATE TABLE CHITIETPHIEUNHAPTHUOC(
	MAPHIEUNHAP INT NOT NULL,
	MATHUOC INT NOT NULL,
	SOLUONG INT NULL,
	NGAYSX DATE NULL,
	NGAYHETHAN DATE NULL,
	GIANHAP MONEY NULL,
	GIABANLE MONEY NULL,
	MAHSX INT NULL,
	MANHACC INT  NULL,
	PRIMARY KEY (MAPHIEUNHAP,MATHUOC)
)
GO

--23 TẠO BẢNG LOAITHUOC
CREATE TABLE LOAITHUOC(
	MALOAITHUOC INT IDENTITY(1,1)  PRIMARY KEY NOT NULL,
	TENLOAI NVARCHAR(50)
)
GO



--24 TẠO BẢNG HANGSANXUAT
CREATE TABLE HANGSANXUAT(
	MAHSX INT PRIMARY KEY IDENTITY(1,1),
	TENHSX NVARCHAR(100),
	DIACHI NVARCHAR(250),
	MAQUOCGIA INT
)
GO


--25 TẠO BẢNG NHANCUNGCAP
CREATE TABLE NHACUNGCAP(
	MANHACC INT IDENTITY(1,1) NOT NULL,
	TENNHACC NVARCHAR(100) NULL,
	DIACHI NVARCHAR(100) NULL,
	SODT VARCHAR(20) NULL,
	EMAIL NVARCHAR(50) NULL,
	MAQUOCGIA INT NULL,
	PRIMARY KEY (MANHACC)
)
GO

--26 TẠO BẢNG QUOCGIA
CREATE TABLE QUOCGIA
(
	MAQUOCGIA INT IDENTITY(1,1) NOT NULL,
	TENQUOCGIA NVARCHAR(50)
	PRIMARY KEY (MAQUOCGIA)
)
GO











--------------------------------------------FOREIGN KEYS ------------------------------------------------------------------------------------------
--NOTE: FK CHO BẢNG NÀO THÌ GHI BẢNG ĐÓ
GO

--1. BẢNG TAIKHOAN
ALTER TABLE dbo.TAIKHOAN ADD CONSTRAINT FK_TAIKHOAN_PHANQUYEN FOREIGN KEY (MAPHANQUYEN)  REFERENCES dbo.PHANQUYEN(MAPHANQUYEN)
GO


--2. BẢNG HOADON

ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_PHIEUKHAM FOREIGN KEY (MAPHIEUKHAM) REFERENCES PHIEUKHAM(MAPHIEUKHAM)
GO



--3. PHIEUKHAM

ALTER TABLE PHIEUKHAM  ADD CONSTRAINT FK_PHIEUKHAM_HINHTHUCKHAM FOREIGN KEY(MAHINHTHUCKHAM) REFERENCES HINHTHUCKHAM(MAHINHTHUCKHAM)
GO

ALTER TABLE PHIEUKHAM  ADD CONSTRAINT FK_PHIEUKHAM_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
GO


ALTER TABLE PHIEUKHAM  ADD CONSTRAINT FK_PHIEUKHAM_BENHNHAN FOREIGN KEY(MABN) REFERENCES BENHNHAN(MABN)
GO

--4. KHOA
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_KHOA FOREIGN KEY (MAKHOA) REFERENCES dbo.KHOA(MAKHOA)
GO

--5. CHITIETDONTHUOC
ALTER TABLE CHITIETDONTHUOC ADD CONSTRAINT CTDT_MADONTHUOC_FK FOREIGN KEY(MADONTHUOC) REFERENCES DONTHUOC(MADONTHUOC)

ALTER TABLE CHITIETDONTHUOC ADD CONSTRAINT CTDT_MATHUOC_FK FOREIGN KEY(MATHUOC) REFERENCES THUOC(MATHUOC)
GO

--6.THUOC
ALTER TABLE THUOC ADD CONSTRAINT THUOC_DONVITINH_FK FOREIGN KEY(DONVITINH) REFERENCES DONVITINH(MADVT)
ALTER TABLE THUOC ADD CONSTRAINT THUOC_LOAITHUOC_FK FOREIGN KEY(LOAITHUOC) REFERENCES LOAITHUOC(MALOAITHUOC)
GO

---7. DONTHUOC
ALTER TABLE DONTHUOC ADD CONSTRAINT DONTHUOC_MAPHIEUKHAM_FK FOREIGN KEY(MAPHIEUKHAM) REFERENCES PHIEUKHAM(MAPHIEUKHAM)
GO

--8. CHITIETPHIEUNHAPTHUOC
ALTER TABLE CHITIETPHIEUNHAPTHUOC
ADD CONSTRAINT FK_CHITIETPHIEUNHAPTHUOC_PHIEUNHAP
FOREIGN KEY  (MAPHIEUNHAP)
REFERENCES PHIEUNHAP(MAPHIEUNHAP)
 GO
 
ALTER TABLE CHITIETPHIEUNHAPTHUOC
ADD CONSTRAINT FK_CHITIETPHIEUNHAPTHUOC_THUOC
FOREIGN KEY  (MATHUOC)
REFERENCES THUOC(MATHUOC)
GO
 
ALTER TABLE CHITIETPHIEUNHAPTHUOC
ADD CONSTRAINT FK_CHITIETPHIEUNHAPTHUOC_HANGSANXUAT
FOREIGN KEY  (MAHSX)
REFERENCES HANGSANXUAT(MAHSX)
GO
 
ALTER TABLE CHITIETPHIEUNHAPTHUOC
ADD CONSTRAINT FK_CHITIETPHIEUNHAPTHUOC_NHACUNGCAP
FOREIGN KEY  (MANHACC)
REFERENCES NHACUNGCAP(MANHACC)
GO
 
 
--9. VATTUYTE
ALTER TABLE VATTUYTE
ADD CONSTRAINT FK_VATTUYTE_DONVITINH
FOREIGN KEY  (MADVT)
REFERENCES DONVITINH(MADVT)
GO
 
 
--10. CHITIETNHAPVATTU
ALTER TABLE CHITIETNHAPVATTU
ADD CONSTRAINT FK_CHITIETNHAPVATTU_PHIEUNHAP
FOREIGN KEY  (MAPHIEUNHAP)
REFERENCES PHIEUNHAP(MAPHIEUNHAP)
GO
 
ALTER TABLE CHITIETNHAPVATTU
ADD CONSTRAINT FK_CHITIETNHAPVATTU_NHACUNGCAP
FOREIGN KEY  (MANHACC)
REFERENCES NHACUNGCAP(MANHACC)
GO
 
ALTER TABLE CHITIETNHAPVATTU
ADD CONSTRAINT FK_CHITIETNHAPVATTU_HANGSANXUAT
FOREIGN KEY  (MAHSX)
REFERENCES HANGSANXUAT(MAHSX)
GO
 
ALTER TABLE CHITIETNHAPVATTU
ADD CONSTRAINT FK_CHITIETNHAPVATTU_VATTUYTE
FOREIGN KEY  (MAVTYT)
REFERENCES VATTUYTE(MAVTYT)
GO
 
--11. HANGSANXUAT

ALTER TABLE HANGSANXUAT
ADD CONSTRAINT FK_HANGSANXUAT_QUOCGIA
FOREIGN KEY  (MAQUOCGIA)
REFERENCES QUOCGIA(MAQUOCGIA)
GO
--12. NHANVIEN

ALTER TABLE NHANVIEN 
ADD CONSTRAINT FK_NHANVIEN_CHUCDANH 
FOREIGN KEY (MACHUCDANH)
REFERENCES CHUCDANH(MACHUCDANH)
ALTER TABLE NHANVIEN 
ADD CONSTRAINT FK_NHANVIEN_CHUCVU 
FOREIGN KEY (MACHUCVU)
REFERENCES CHUCVU(MACHUCVU)
GO
--13. PHIEUNHAP

ALTER TABLE PHIEUNHAP 
ADD CONSTRAINT FK_PHIEUNHAP_NHANVIEN 
FOREIGN KEY (MANV)
REFERENCES NHANVIEN(MANV)
GO

--14. NHACUNGCAP
ALTER TABLE dbo.NHACUNGCAP ADD CONSTRAINT FK_NHACUNGCAP_QUOCGIA FOREIGN KEY (MAQUOCGIA) REFERENCES dbo.QUOCGIA(MAQUOCGIA)
GO

--15. CANLAMSANG

ALTER TABLE dbo.CANLAMSANG ADD CONSTRAINT FK_CANLAMSANG_LOAICANLAMSANG FOREIGN KEY (MALOAICLS) REFERENCES dbo.LOAICANLAMSANG(MALOAICLS)
GO

--16. DICHVUCLS
ALTER TABLE dbo.DICHVUCLS ADD CONSTRAINT FK_DICHVUCLS_PHIEUKHAM FOREIGN KEY (MAPHIEUKHAM) REFERENCES dbo.PHIEUKHAM(MAPHIEUKHAM)
GO


--17. CHITIETCLS
ALTER TABLE dbo.CHITIETCLS ADD CONSTRAINT FK_CHITIETCLS_CANLAMSANG FOREIGN KEY (MACLS) REFERENCES dbo.CANLAMSANG(MACLS)
GO

ALTER TABLE dbo.CHITIETCLS ADD CONSTRAINT FK_CHITIETCLS_DICHVUCLS FOREIGN KEY (MADICHVUCLS) REFERENCES dbo.DICHVUCLS(MADICHVUCLS)
GO





--------------------------------------------STORE PROCEDURE ---------------------------------------------------------------------------------------

--NOTE: STORE PROCEDURE CHO BẢNG NÀO THÌ GHI BẢNG ĐÓ, NHỚ GHI THỨ TỰ VÀ GHI TÊN

--1. BẢNG TAIKHOAN
--1.1 SP_INSERT_TAIKHOAN
CREATE PROC SP_INSERT_TAIKHOAN
	@TENDANGNHAP VARCHAR(50),
	@MATKHAU VARCHAR(50),
	@TENHIENTHI NVARCHAR(50),
	@MAPHANQUYEN INT,
	@TRANGTHAI BIT
AS
BEGIN
	INSERT INTO dbo.TAIKHOAN 
	        ( TENDANGNHAP ,
	          MATKHAU ,
	          TENHIENTHI ,
	          MAPHANQUYEN ,
	          TRANGTHAI
	        )
	VALUES  ( @TENDANGNHAP , -- TENDANGNHAP - varchar(50)
	          @MATKHAU , -- MATKHAU - varchar(50)
	         N''+ @TENHIENTHI , -- TENHIENTHI - nvarchar(50)
	          @MAPHANQUYEN , -- MAPHANQUYEN - int
	          @TRANGTHAI  -- TRANGTHAI - bit
	        )
END
GO



--1.2 SP_UPDATE_TAIKHOAN
CREATE PROC SP_UPDATE_TAIKHOAN
	@MATK INT,
	@MATKHAU VARCHAR(50),
	@TENHIENTHI NVARCHAR(50),
	@MAPHANQUYEN INT,
	@TRANGTHAI BIT
AS
BEGIN 
	UPDATE dbo.TAIKHOAN SET MATKHAU = @MATKHAU , TENHIENTHI = @TENHIENTHI , MAPHANQUYEN=@MAPHANQUYEN, TRANGTHAI = @TRANGTHAI
	WHERE MATK = @MATK
END
GO



--1.3 SP_LOGIN





--2. BẢNG PHANQUYEN
--2.1 SP_INSERT_PHANQUYEN
CREATE PROC SP_INSERT_PHANQUYEN
	@QUYEN INT,
	@GHICHU NVARCHAR(250)
AS
BEGIN
	INSERT INTO dbo.PHANQUYEN
	        (  QUYEN, GHICHU )
	VALUES  ( @QUYEN, -- QUYEN - int
	          N''+@GHICHU  -- GHICHU - nvarchar(250)
	          )
END
GO


--3. Bảng NHANVIEN
--3.1 SP_INSERT_NHANVIEN
CREATE PROC SP_INSERT_NHANVIEN
@MANV INT,	
@HOTEN NVARCHAR(50),
@GIOITINH BIT,
@SODT VARCHAR(20),
@EMAIL VARCHAR(50),
@MAKHOA INT,
@MACHUCDANH INT,
@MACHUCVU INT
AS
BEGIN
	INSERT INTO NHANVIEN VALUES(@MANV,@HOTEN,@GIOITINH,@SODT,@EMAIL,@MAKHOA,@MACHUCDANH,@MACHUCVU)
END
GO
--3.2 SP_UPDATE_NHANVIEN
CREATE PROC SP_UPDATE_NHANVIEN
@MANV INT,
@HOTEN NVARCHAR(50),
@GIOITINH BIT,
@SODT VARCHAR(20),
@EMAIL VARCHAR(50),
@MAKHOA INT,
@MACHUCDANH INT,
@MACHUCVU INT
AS
BEGIN
	UPDATE NHANVIEN SET  
						HOTEN=@HOTEN,
						GIOITINH=@GIOITINH,
						SODT=@SODT,
						EMAIL=@EMAIL,
						MAKHOA=@MAKHOA,
						MACHUCDANH=@MACHUCDANH,
						MACHUCVU=@MACHUCVU
	WHERE MANV=@MANV
END
GO
--3.3 SP_TIMKIEM_NHANVIEN
	CREATE PROC SP_TIMKIEM_NHANVIEN
@MANV INT
AS
BEGIN
	SELECT *
	FROM NHANVIEN NV
	WHERE NV.MANV=@MANV
END
GO

--4. Bảng CHUCVU
--4.1 SP_INSERT_CHUCVU
	CREATE PROC SP_INSERT_CHUCVU
@MACHUCVU INT,
@TENCHUCVU NVARCHAR(50)
AS
BEGIN
	INSERT INTO CHUCVU VALUES(@MACHUCVU,@TENCHUCVU)
END
GO
--4.2 SP_UPDATE_CHUCVU
CREATE PROC SP_UPDATE_CHUCVU
@MACHUCVU INT,
@TENCHUCVU NVARCHAR(50)
AS
BEGIN
	UPDATE CHUCVU SET
					  TENCHUCVU=@TENCHUCVU
	WHERE MACHUCVU=@MACHUCVU
END
GO
--4.3 SP_TIMKIEM_CHUCVU
CREATE PROC SP_TIMKIEM_CHUCVU
@MACHUCVU INT
AS
BEGIN
	SELECT *
	FROM CHUCVU CV
	WHERE CV.MACHUCVU=@MACHUCVU
END
GO
--5 Bảng CHUCDANH
--5.1 SP_INSERT_CHUCDANH
CREATE PROC SP_INSERT_CHUCDANH
@MACHUCDANH INT,
@TENCHUCDANH NVARCHAR(50)
AS
BEGIN
	INSERT INTO CHUCDANH VALUES(@MACHUCDANH,@TENCHUCDANH)
END
GO
--5.2 SP_UPDATE_CHUCDANH
CREATE PROC SP_UPDATE_CHUCDANH
@MACHUCDANH INT,
@TENCHUCDANH NVARCHAR(50)
AS
BEGIN
	UPDATE CHUCDANH SET
						TENCHUCDANH=@TENCHUCDANH
	WHERE MACHUCDANH=@MACHUCDANH
END
GO
--5.3 SP_TIMKIEM_CHUCDANH
CREATE PROC SP_TIMKIEM_CHUCDANH
 @MACHUCDANH INT
AS
BEGIN
	SELECT *
	FROM CHUCDANH CD
	WHERE CD.MACHUCDANH=@MACHUCDANH
END
GO
--6. Bảng NHAPPHIEU
--6.1 SP_INSERT_PHIEUNHAP
CREATE PROC SP_INSERT_PHIEUNHAP
 @MAPHIEUNHAP INT,
 @MAMV INT,
 @NGAYNHAP DATE
 AS
 BEGIN
	INSERT INTO PHIEUNHAP VALUES(@MAPHIEUNHAP,@MAMV,@NGAYNHAP)
 END
 GO
--6.2 SP_UPDATE_PHIEUNHAP
CREATE PROC SP_UPDATE_PHIEUNHAP
 @MAPHIEUNHAP INT,
 @MAMV INT,
 @NGAYNHAP DATE
 AS
 BEGIN
	UPDATE PHIEUNHAP SET
						 MANV=@MAMV,
						 NGAYNHAP=@NGAYNHAP
WHERE MAPHIEUNHAP=@MAPHIEUNHAP 
END
 GO
--6.3 SP_TIMKIEM_PHIEUNHAP
CREATE PROC SP_TIMKIEM_PHIEUNHAP
@MAPHIEUNHAP INT
AS
BEGIN
	SELECT *
	FROM PHIEUNHAP PN
	WHERE PN.MAPHIEUNHAP=@MAPHIEUNHAP
END
GO

--7. Bảng NHACUNGCAP
--7.1 SP_INSERT_NHACUNGCAP
CREATE PROC SP_INSERT_NHACUNGCAP
 @MANHACC INT,
 @TENNHACC NVARCHAR(100),
 @DIACHI NVARCHAR(100),
 @SODT VARCHAR(20),
 @EMAIL NVARCHAR(50),
 @MAQUOCGIA INT
 AS
 BEGIN
	INSERT INTO NHACUNGCAP VALUES(@MANHACC,@TENNHACC,@DIACHI,@SODT,@EMAIL,@MAQUOCGIA)
 END
 GO
--7.2 SP_UPDATE_NHACUNGCAP
CREATE PROC SP_UPDATE_NHACUNGCAP
 @MANHACC INT,
 @TENNHACC NVARCHAR(100),
 @DIACHI NVARCHAR(100),
 @SODT VARCHAR(20),
 @EMAIL NVARCHAR(50),
 @MAQUOCGIA INT
 AS
 BEGIN
UPDATE NHACUNGCAP SET		TENNHACC=@TENNHACC,
						  DIACHI=@DIACHI,
						  SODT=@SODT,
						  EMAIL=@EMAIL,
						  MAQUOCGIA=@MAQUOCGIA
WHERE MANHACC = @MANHACC
 END
 GO
--7.3 SP_TIMKIEM_NHACUNGCAP
CREATE PROC SP_TIMKIEM_NHACUNGCAP
@MANHACC INT
AS
BEGIN
	SELECT *
	FROM NHACUNGCAP NCC
	WHERE NCC.MANHACC=@MANHACC
END
GO

--BẢNG PHIEUKHAM
--8.1 SP_INSERT PHIEU KHAM

CREATE PROC SP_Insert_Phieukham
@MABN INT,
@NHANVIEN INT,
@CHUANDOAN NVARCHAR(250),
@MAHINHTHUCKHAM INT,
@NGAYKHAM DATE,
@KETLUAN NVARCHAR(50),
@HOANTHANH BIT
AS
BEGIN 
INSERT INTO PHIEUKHAM VALUES (@MABN,
@NHANVIEN,
@CHUANDOAN,
@MAHINHTHUCKHAM,
@NGAYKHAM,
@KETLUAN,
@HOANTHANH
)
END
GO

--8.2 SP  UPDATE PHIEUKHAM

CREATE PROC SP_Update_Phieukham
@MAPHIEUKHAM INT,
@MABN INT,
@NHANVIEN INT,
@CHUANDOAN NVARCHAR(250),
@MAHINHTHUCKHAM INT,
@NGAYKHAM DATE,
@KETLUAN NVARCHAR(50),
@HOANTHANH BIT
AS
BEGIN 
UPDATE PHIEUKHAM SET 
MABN = @MABN,
NHANVIEN = @NHANVIEN,
CHUANDOAN = @CHUANDOAN,
MAHINHTHUCKHAM = @MAHINHTHUCKHAM,
NGAYKHAM = @NGAYKHAM,
KETLUAN = @KETLUAN,
HOANTHANH = @HOANTHANH
WHERE MAPHIEUKHAM = @MAPHIEUKHAM
END

GO

--8.3 SP SELECT ALL PHIEUKHAM

CREATE PROC SP_Select_Phieukham
AS
BEGIN 
SELECT * FROM PHIEUKHAM
END
GO

CREATE PROC SP_Select_Danhsachkham
AS
BEGIN 
SELECT * FROM DANHSACHKHAM
END
GO

--8.4 SP SEARCH PHIEUKHAM BẰNG ID


CREATE PROC SP_Search_Phieukham
@MAPHIEU INT
AS
BEGIN 
SELECT * FROM PHIEUKHAM WHERE MAPHIEUKHAM = @MAPHIEU 
END
GO


--BẢNG BENHNHAN

--9.1 SP INSERT BENHNHAN

CREATE PROC SP_Insert_Benhnhan 
@HOTEN nvarchar(50),@GIOITINH BIT,@NGAYSINH DATE,@SOCMND NCHAR(10),@DIACHI NVARCHAR(250),@SODT VARCHAR(20)
AS 
BEGIN 
INSERT INTO BENHNHAN VALUES (@HOTEN,@GIOITINH,@NGAYSINH,@SOCMND,@DIACHI,@SODT)
END
GO

--9.2 SP UPDATE  BENHNHAN


CREATE PROC SP_Update_Benhnhan
@MABN  INT,
@HOTEN nvarchar(50),
@GIOITINH BIT,
@NGAYSINH DATE,
@SOCMND NCHAR(10),
@DIACHI NVARCHAR(250),
@SODT VARCHAR(20)
AS 
BEGIN 
UPDATE BENHNHAN SET HOTEN = @HOTEN, GIOITINH = @GIOITINH, NGAYSINH = @NGAYSINH, SOCMND = @SOCMND, DIACHI = @DIACHI, SODT = @SODT
WHERE MABN = @MABN
END
GO

--9.3 SP SELECT ALL BENHNHAN

CREATE PROC SP_Select_Benhnhan
AS
BEGIN 
SELECT * FROM BENHNHAN 
END
GO


--9.4 SP SEARCH  BENHNHAN  BANG ID


CREATE PROC SP_Search_Benhnhan
@HOTEN NVARCHAR(50)
AS
BEGIN
SELECT * FROM BENHNHAN BN WHERE BN.HOTEN = @HOTEN  
END
GO


--BẢNG HINHTHUCKHAM
--10.1 SP INSERT HINHTHUCKHAM

CREATE PROC SP_Insert_Hinhthuckham
@TENHINHTHUCKHAM NVARCHAR(100)
AS 
BEGIN
INSERT INTO HINHTHUCKHAM VALUES (@TENHINHTHUCKHAM)
END

GO


--10.2 SP UPDATE HINHTHUCKHAM

CREATE PROC SP_Update_Hinhthuckham
@MAHINHTHUCKHAM INT,
@TENHINHTHUCKHAM NVARCHAR(100)
AS 
BEGIN
UPDATE HINHTHUCKHAM SET TENHINHTHUCKHAM = @TENHINHTHUCKHAM 
WHERE MAHINHTHUCKHAM = @MAHINHTHICKHAM
END
GO

--10.3 SP SELECT ALL HINHTHUCKHAM


CREATE PROC SP_Select_Hinhthuckham
AS
BEGIN 
SELECT * FROM HINHTHUCKHAM
END
GO

--10.4 SP SEARCH HINHTHUCKHAM QUA ID

CREATE PROC SP_Search_Hinhthuckham
@MAHINHTHUCKHAM INT
AS
BEGIN 
SELECT * FROM HINHTHUCKHAM WHERE MAHINHTHUCKHAM = @MAHINHTHUCKHAM 
END
GO

--BẢNG HOADON

--11.1 SP INSERT  HOADON

CREATE PROC SP_Insert_Hoadon
@MAPHIEUKHAM int,
@TONGCONG money
AS 
BEGIN 
INSERT INTO HOADON VALUES (@MAPHIEUKHAM,
@TONGCONG )
END

GO


--11.2 SP UPDATE HOADON


CREATE PROC SP_Update_Hoadon
@MAHOADON INT,
@MAPHIEUKHAM int,
@TONGCONG money
AS 
BEGIN 
UPDATE HOADON SET MAPHIEUKHAM = @MAPHIEUKHAM,TONGCONG = @TONGCONG 
WHERE MAHOADON = @MAHOADON
END
GO


--11.3 SP SELECT ALL HOADON


CREATE PROC SP_Select_Hoadon
AS
BEGIN 
SELECT * FROM HOADON
END
GO

--11.4 SEARCH HOADON

CREATE PROC SP_Search_Hoadon
@MAHD INT
AS
BEGIN 
SELECT * FROM HOADON WHERE MAHOADON = @MAHD 
END
GO

--BẢNG DANHSACHKHAM
--12.1 SP INSERT DANHSACHKHAM

CREATE PROC SP_Insert_Danhsachkham
@MAPHIEUKHAM int,
@NGAYKHAM date,
@HOANTHANH bit
AS 
BEGIN
INSERT INTO DANHSACHKHAM VALUES (@MAPHIEUKHAM,
@NGAYKHAM,
@HOANTHANH)
END

GO


--12.2 SP UPDATE DANHSACHKHAM


CREATE PROC SP_Update_Danhsachkham
@MADSK INT,
@MAPHIEUKHAM int,
@NGAYKHAM date,
@HOANTHANH bit
AS 
BEGIN
UPDATE DANHSACHKHAM SET MAPHIEUKHAM=@MAPHIEUKHAM,
NGAYKHAM=@NGAYKHAM,
HOANTHANH=@HOANTHANH
WHERE MADSK = @MADSK
END

GO

--12.3 SP SELECT ALL DANHSACHKHAM

CREATE PROC SP_Select_Danhsachkham
AS
BEGIN 
SELECT * FROM DANHSACHKHAM
END
GO

--12.4 SP SEARCH DANHSACHKHAM


CREATE PROC SP_Search_Danhsachkham
@MADSK INT
AS
BEGIN 
SELECT * FROM DANHSACHKHAM WHERE MADSK = @MADSK 
END
GO

--- BẢNG DONTHUOC

-- 13.1 SP_InsertDonThuoc

CREATE PROC SP_InsertDonThuoc
	@Maphieukham INT
AS
	DECLARE @TONGCONG INT
	DECLARE @MATHUOC INT
	SET @MATHUOC = (SELECT  FROM MADONTHUOC )
	DECLARE @GIABANLE INT
	SET @GIABANLE =  (SELECT GIABANLE FROM CHITIETPHIEUNHAPTHUOC, THUOC WHERE THUOC.MATHUOC = CHITIETPHIEUNHAPTHUOC.MATHUOC AND THUOC.MATHUOC = @MATHUOC)
	IF (EXISTS (SELECT * FROM PHIEUKHAM WHERE MAPHIEUKHAM = @Maphieukham))	-- ma phieu kham ton tại
	BEGIN
		INSERT INTO DONTHUOC(MAPHIEUKHAM, TONGCONG) VALUES (@Maphieukham, @Tongcong)
	END

GO

--- 13.2 SP_UpdateDonThuoc

CREATE PROC SP_UpdateDonThuoc
	@MaDT int,
	@Maphieukham INT,
	@Tongcong MONEY
AS
	IF (EXISTS (SELECT * FROM DONTHUOC WHERE MADONTHUOC = @MaDT))	-- ma phieu kham ton tại
	BEGIN
		UPDATE DONTHUOC SET MAPHIEUKHAM = @Maphieukham, TONGCONG = @Tongcong WHERE MADONTHUOC = @MaDT
	END

GO

--- BẢNG CHITIETHOADON

--- 14.1 SP_InsertCTDT

CREATE PROC SP_InsertCTDT
	@madthuoc int,
	@mathuoc int,
	@soluong int,
	@huongdan text
AS 
	IF EXISTS (SELECT * FROM CHITIETDONTHUOC WHERE MADONTHUOC = @madthuoc)
	BEGIN
		WHILE EXISTS (SELECT * FROM THUOC WHERE MATHUOC = @mathuoc)
		BEGIN
		INSERT INTO CHITIETDONTHUOC(MADONTHUOC, MATHUOC, SOLUONG, HUONGDAN) VALUES (@madthuoc, @mathuoc, @soluong, @huongdan)
		END
	END

GO

--- 14.2 SP_UpdateCTDT

CREATE PROC SP_UpdateCTDT
	@madthuoc int,
	@mathuoc int,
	@soluong int,
	@huongdan text
AS 
	IF EXISTS (SELECT * FROM CHITIETDONTHUOC WHERE MADONTHUOC = @madthuoc)
	BEGIN
		UPDATE CHITIETDONTHUOC SET MATHUOC = @mathuoc, SOLUONG = @soluong, HUONGDAN = @huongdan
		WHERE MADONTHUOC = @madthuoc
	END

GO

--- BẢNG THUOC
--- 15.1 SP_InsertThuoc

CREATE PROC SP_InsertThuoc
	@tenthuoc nvarchar(50),
	@donvitinh int,
	@loaithuoc int,
	@soluongton int,
	@ghichu text
AS
	BEGIN 
		INSERT INTO THUOC(TENTHUOC, DONVITINH, LOAITHUOC, SOLUONGTON, GHICHU) VALUES (@tenthuoc, @donvitinh, @loaithuoc, @soluongton, @ghichu)
	END

GO

--- 15.2 SP_UpdateThuoc

CREATE PROC SP_UpdateThuoc
	@mathuoc int,
	@tenthuoc nvarchar(50),
	@donvitinh int,
	@loaithuoc int,
	@soluongton int,
	@ghichu text
AS
	BEGIN 
		UPDATE THUOC SET TENTHUOC = @tenthuoc, DONVITINH = @donvitinh, LOAITHUOC = @loaithuoc, SOLUONGTON = @soluongton, GHICHU = @ghichu
		WHERE MATHUOC = @mathuoc
	END

GO	

--- BẢNG LOAITHUOC
--- 16.1 SP_InsertLoaiThuoc

CREATE PROC SP_InsertLoaiThuoc
	@tenloaithuoc nvarchar(50)
AS
	IF NOT EXISTS (SELECT * FROM LOAITHUOC WHERE TENLOAI = @tenloaithuoc)
	BEGIN 
		INSERT INTO LOAITHUOC(TENLOAI) VALUES (@tenloaithuoc)
	END

GO

--- 16.2 SP_UpdateLoaiThuoc

CREATE PROC SP_UpdateLoaiThuoc
	@maloaithuoc int,
	@tenloaithuoc nvarchar(50)
AS
	IF NOT EXISTS (SELECT * FROM LOAITHUOC WHERE MALOAITHUOC = @maloaithuoc)
	BEGIN
		UPDATE LOAITHUOC SET TENLOAI = @tenloaithuoc
		WHERE MALOAITHUOC = @maloaithuoc
	END

GO

--- BẢNG DONVITINH
--- 17.1 SP_InsertDVT

CREATE PROC SP_InsertDVT
	@tendvt nvarchar(50)
AS
	IF NOT EXISTS (SELECT * FROM DONVITINH WHERE TENDVT = @tendvt)
	BEGIN 
		INSERT INTO DONVITINH(TENDVT) VALUES (@tendvt)
	END

GO


--- 17.2  SP_UpdateDVT

CREATE PROC SP_UpdateDVT
	@madvt int,
	@tendvt nvarchar(50)
AS
	IF NOT EXISTS (SELECT * FROM DONVITINH WHERE MADVT = @madvt)
	BEGIN
		UPDATE DONVITINH SET TENDVT = @tendvt
		WHERE MADVT = @madvt
	END

GO






--- BẢNG PHIEUNHAP
--- 18.1 SP_InsertCHITIETPHIEUNHAPTHUOC
Create Procedure SP_InsertCHITIETPHIEUNHAPTHUOC
@SoLuong int,
@NgaySX date,
@NgayHH date,
@GiaNhap money,
@GiaBanLe money,
@MaHSX int,
@MaNCC int
as
begin
insert into CHITIETPHIEUNHAPTHUOC(SOLUONG, NGAYSX, NGAYHETHAN, GIANHAP, GIABANLE, MAHSX, MANHACC)
VALUES (@SoLuong, @NgaySX, @NgayHH, @GiaNhap, @GiaBanLe,@MaHSX, @MaNCC)
end
 
 SP_UpdateCHITIETPHIEUNHAPTHUOC
Create Procedure SP_UpdateCHITIETPHIEUNHAPTHUOC
@MAPHIEUNHAP int,
@MATHUOC int,
@SoLuong int,
@NgaySX date,
@NgayHH date,
@GiaNhap money,
@GiaBanLe money,
@MaHSX int,
@MaNCC int
as
begin
update CHITIETPHIEUNHAPTHUOC
set      	SOLUONG = @SoLuong , NGAYSX = @NgaySX , NGAYHETHAN = @NgayHH, GIANHAP = @GiaNhap , GIABANLE = @GiaBanLe, MAHSX = @MaHSX, MANHACC = @MaNCC
where MAPHIEUNHAP = @MAPHIEUNHAP and MATHUOC = @MATHUOC
end
 
 SP_SelectAllCHITIETPHIEUNHAPTHUOC
Create Procedure SP_SelectAllCHITIETPHIEUNHAPTHUOC
as
begin
Select * From CHITIETPHIEUNHAPTHUOC
end
 
SP_SearchCHITIETPHIEUNHAPTHUOC
Create Procedure SP_SearchCHITIETPHIEUNHAPTHUOC
@MAPHIEUNHAP int
as
begin
Select * From CHITIETPHIEUNHAPTHUOC where MAPHIEUNHAP = @MAPHIEUNHAP
end

 
 
--- BẢNG CHITIETNHAPVATTU
--- 19.1 SP_InsertCHITIETNHAPVATTU
Create Procedure SP_InsertCHITIETNHAPVATTU
 
@SoLuong int,
@MaNHSX int,
@NgaySX date,
@NgayHH date,
@GiaNhap money,
@GiaBanLe money,
@MaNCC int
as
begin
insert into CHITIETNHAPVATTU (SOLUONG, MANHSX, NGAYSX, NGAYHETHAN, GIANHAP, GIABANLE, MANHACC)
VALUES (@SoLuong, @MaNHSX, @NgaySX, @NgayHH, @GiaNhap, @GiaBanLe, @MaNCC)
end
 
 --- 19.2  SP_UpdateCHITIETNHAPVATTU
Create Procedure SP_UpdateCHITIETNHAPVATTU
@MaPhieuNhap int,
@MaVTYT int,
@SoLuong int,
@MaNHSX int,
@NgaySX date,
@NgayHH date,
@GiaNhap money,
@GiaBanLe money,
@MaNCC int
as
begin
update CHITIETNHAPVATTU
set SOLUONG = @SoLuong ,
MANHSX = @MaNHSX,
NGAYSX = @NgaySX ,
NGAYHETHAN =  @NgayHH,
GIANHAP = @GiaNhap ,
GIABANLE = @GiaBanLe ,
MANHACC = @MaNCC
where MAPHIEUNHAP = @MaPhieuNhap and MAVTYT = @MaVTYT
end
 
 --- 19.3  SP_SelectAllCHITIETNHAPVATTU
Create Procedure SP_SelectAllCHITIETNHAPVATTU
as
begin
Select * From CHITIETNHAPVATTU
end
 

---19.4 SP_SearchCHITIETNHAPVATTU
Create Procedure SP_SearchCHITIETNHAPVATTU
@MaPhieuNhap int
as
begin
Select * From CHITIETNHAPVATTU where MAPHIEUNHAP = @MaPhieuNhap
end
 
 
 
 
 
--- BẢNG VATTUYTE
--20.1 SP_InsertVATTUYTE
Create Procedure SP_InsertVATTUYTE
@MaVTYT int,
@TenVT nvarchar(100),
@MaDVT int,
@SoLuongTon int
as
begin
insert into VATTUYTE ( TENVATTU, MADVT, SOLUONGTON)
values (@TenVT, @MaDVT, @SoLuongTon)
END
 
 --- 20.2 SP_UpdateVATTUYTE
Create Procedure SP_UpdateVATTUYTE
@MaVTYT int,
@TenVT nvarchar(100),
@MaDVT int,
@SoLuongTon int
as
begin
update VATTUYTE
set TENVATTU = @TenVT, MADVT = @TenVT, SOLUONGTON = @SoLuongTon
where MAVTYT = @MaVTYT
end
 
 --- 20.3  SP_SelectAllVATTUYTE
Create Procedure SP_SelectAllVATTUYTE
as
begin
select * From VATTUYTE
end
 
 --- 20.4  SP_SearchVATTUYTE
Create Procedure SP_SearchVATTUYTE
@MaVTYT int
as
begin
select * From VATTUYTE where MAVTYT = @MaVTYT
end
 
 
 
--- BẢNG HANGSANXUAT
--- 21.1 SP_InsertHANGSANXUAT

Create Procedure SP_InsertHANGSANXUAT
@TenNHSX nvarchar(100),
@DiaChi nvarchar(100),
@MaQuocGia int
as
begin
insert into HANGSANXUAT ( TENHSX, DIACHI, MAQUOCGIA)
VALUES (@TenNHSX, @DiaChi, @MaQuocGia)
end
 
 ---21.2 SP_UpdateHANGSANXUAT

Create Procedure SP_UpdateHANGSANXUAT
@MaHSX int,
@TenNHSX nvarchar(100),
@DiaChi nvarchar(100),
@MaQuocGia int
as
begin
update HANGSANXUAT
set MAHSX = @MaHSX, TENHSX = @TenNHSX, DIACHI = @DiaChi, MAQUOCGIA = @MaQuocGia
where MAHSX = @MaHSX
end
 
--- 21.3 SP_SelectAllHANGSANXUAT
Create Procedure SP_SelectAllHANGSANXUAT
as
begin
Select * From HANGSANXUAT
end
 
 --- 21.4  SP_SearchHANGSANXUAT
Create Procedure SP_SearchHANGSANXUAT
@MaHSX int
as
begin
Select * From HANGSANXUAT where MAHSX = @MaHSX
end 
 
 
 
 
--- BẢNG QUOCGIA
--- 22.1 SP_InsertQUOCGIA
Create Procedure SP_InsertQUOCGIA
@TenQuocGia nvarchar(50)
as
begin
insert into QUOCGIA (TENQUOCGIA)
values (@TenQuocGia)
end
 
 --- 22.2 SP_UpdateQUOCGIA
Create Procedure SP_UpdateQUOCGIA
@MaQuocGia int,
@TenQuocGia nvarchar(50)
as
begin
update QUOCGIA
set TENQUOCGIA = @TenQuocGia
where MAQUOCGIA = @MaQuocGia
end
 
 --- 22.3 SP_SelectAllQUOCGIA
Create Procedure SP_SelectAllQUOCGIA
as
begin
Select * From QUOCGIA
end
 
 
 --- 22.4 SP_SearchQUOCGIA
Create Procedure SP_SearchQUOCGIA
@MaQuocGia int
as
begin
Select * From QUOCGIA
where MAQUOCGIA = @MaQuocGia
end


GO
--------------------------------------------TRIGGER -----------------------------------------------------------------------------------------------
-- NOTE: TRIGGER CHO BẢNG NÀO THÌ GHI BẢNG ĐÓ, NHỚ GHI THỨ TỰ VÀ GHI TÊN 
GO


--------------------------------------------INSERT DATA -------------------------------------------------------------------------------------------

--NOTE: INSERT CHO BẢNG NÀO THÌ GHI BẢNG ĐÓ, NHỚ GHI THỨ TỰ VÀ GHI TÊN 

--1. BẢNG PHANQUYEN
EXEC dbo.SP_INSERT_PHANQUYEN @QUYEN = 0, -- int
    @GHICHU = N'Quyền admin' -- nvarchar(250)
GO 



--2. BẢNG TAIKHOAN
EXEC dbo.SP_INSERT_TAIKHOAN @TENDANGNHAP = 'admin', -- varchar(50)
    @MATKHAU = 'admin', -- varchar(50)
    @TENHIENTHI = N'Admin', -- nvarchar(50)
    @MAPHANQUYEN = 1, -- int
    @TRANGTHAI = 1 -- bit
GO

select * from TAIKHOAN

 





 
 



