//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKham.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANLAMSANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CANLAMSANG()
        {
            this.CHITIETCLS = new HashSet<CHITIETCL>();
        }
    
        public int MACLS { get; set; }
        public string TENCLS { get; set; }
        public Nullable<decimal> GIATIEN { get; set; }
        public Nullable<int> MALOAICLS { get; set; }
    
        public virtual LOAICANLAMSANG LOAICANLAMSANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETCL> CHITIETCLS { get; set; }
    }
}
