//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKham.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETCL
    {
        public int MADICHVUCLS { get; set; }
        public int MACLS { get; set; }
        public string KETQUA { get; set; }
    
        public virtual CANLAMSANG CANLAMSANG { get; set; }
        public virtual DICHVUCL DICHVUCL { get; set; }
    }
}
