//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKham.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHAPTHUOC
    {
        public int MAPHIEUNHAP { get; set; }
        public int MATHUOC { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<System.DateTime> NGAYSX { get; set; }
        public Nullable<System.DateTime> NGAYHETHAN { get; set; }
        public Nullable<decimal> GIANHAP { get; set; }
        public Nullable<decimal> GIABANLE { get; set; }
        public Nullable<int> MAHSX { get; set; }
        public Nullable<int> MANHACC { get; set; }
    
        public virtual HANGSANXUAT HANGSANXUAT { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
