//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKham.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int MAHOADON { get; set; }
        public int MAPHIEUKHAM { get; set; }
        public Nullable<decimal> TONGCONG { get; set; }
    
        public virtual PHIEUKHAM PHIEUKHAM { get; set; }
    }
}
