//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKham.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUKHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUKHAM()
        {
            this.DICHVUCLS = new HashSet<DICHVUCL>();
            this.DONTHUOCs = new HashSet<DONTHUOC>();
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public int MAPHIEUKHAM { get; set; }
        public Nullable<int> MABN { get; set; }
        public Nullable<int> MANV { get; set; }
        public string CHUANDOAN { get; set; }
        public Nullable<int> MAHINHTHUCKHAM { get; set; }
        public Nullable<System.DateTime> NGAYKHAM { get; set; }
        public string KETLUAN { get; set; }
        public Nullable<bool> HOANTHANH { get; set; }
        public Nullable<bool> DATHANHTOAN { get; set; }
    
        public virtual BENHNHAN BENHNHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DICHVUCL> DICHVUCLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONTHUOC> DONTHUOCs { get; set; }
        public virtual HINHTHUCKHAM HINHTHUCKHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
