//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKham.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VATTUYTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VATTUYTE()
        {
            this.CHITIETNHAPVATTUs = new HashSet<CHITIETNHAPVATTU>();
        }
    
        public int MAVTYT { get; set; }
        public string TENVATTU { get; set; }
        public Nullable<int> MADVT { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETNHAPVATTU> CHITIETNHAPVATTUs { get; set; }
        public virtual DONVITINH DONVITINH { get; set; }
    }
}
